export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  home: {
    screenTitle: 'Home',
    header: 'Home',
    message: 'Welcome',
    variant: 'App variant: ',
    popularMovies: 'Popular Movies',
    topFeaturedMovies: 'Top Featured',
    getMoviesError:
      'Oops!, there was an error loading the movies page, please try again in a few minutes',
    getMovieError:
      'Oops!, there was an error loading the movie page, please try again in a few minutes',
    mainCarouselButtons: {
      myList: 'My List',
      play: 'Play',
      info: 'Info',
    },
  },
  movieDetail: {
    screenTitle: 'Movie Detail',
    genres: {
      28: 'Action',
      12: 'Adventure',
      16: 'Animation',
      35: 'Comedy',
      80: 'Crime',
      99: 'Documentary',
      18: 'Drama',
      10751: 'Family',
      14: 'Fantasy',
      36: 'History',
      27: 'Horror',
      10402: 'Music',
      9648: 'Mystery',
      10749: 'Romance',
      878: 'Science Fiction',
      10770: 'TV Movie',
      53: 'Thriller',
      10752: 'War',
      37: 'Western',
    },
  },
  login: {
    username: 'Username',
    usernameHint: 'Enter your username',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid credentials',
  },
  profile: {
    screenTitle: 'Profile',
    header: 'Profile',
    logout: 'Logout',
    message: 'This screen has the iOS native large header.',
  },
  search: {
    screenTitle: 'Search',
    searchPlaceholder: 'Search your favorite titles!',
    searchAccessibilityLabel: 'search',
    searchAccessibilityHint: 'Search your favorite movies',
  },
  myList: {
    screenTitle: 'My List',
  },
};
